### PR TITLE
Explicitly specifying no-cache in html head meta

### PR DESCRIPTION
**Pull request by mfkenson**
https://github.com/petercorke/robotics-toolbox-python/issues/182

### CODE REVIEW

**Comment by jhavl** [comment]
This is a good solution to the caching problem especially while the project is under active and breaking development. It would be a good idea to revisit this on version 1.0.0 as caching does greatly improve simulator start up times especially when using robot models containing large Collada or STL meshes.

**Comment by mfkenson** [comment]
Yeah it’s true. 

It would be even better if somehow we could control what needed to be cached. There is a way hacking the URL of requested resource by injecting a fake GET variable to make the browser not to cache the specific resources.

**Comment by mfkenson** [comment]
BTW I have been working on web/app fullstack dev for years. I recently dive into robotics field. If you have any ideas/features in your mind feel free to share the roadmap/TODOs, I could contribute something 🥴.

**Comment by petercorke** [comment]
Good to know! There's a lot we'd like to do on the web graphics side, we should make a list @jhavl

**Pull request merged**
