### PR TITLE
Remove `chdir` and support user-defined robots' meshes to be loaded from their paths.

### PR DESCRIPTION
**Pull request by kxxt**

### CODE REVIEW

**Comment by kxxt** [comment]
A potential security risk: 
We can get any file from the `/retrieve` route.
But since the port isn't exposed to the outside, it should be okay.

**Comment by kxxt** [comment]
And remember to check if this pull request breaks something. I only tested it in one case.

**Comment by kxxt** [comment]
This pull request solves #6.

**Comment by kxxt** [comment]
By the way, is there any plan for supporting simulation of `DHRobot`, since this PR enables meshes to be loaded from anywhere.

**Comment by jhavl** [comment]
Thanks for the pull request - it should solve many issues. I've merged it into the `future` branch to be included in the next release.

**Comment by jhavl** [comment]
Regarding `DHRobot` there is missing simulation logic in Swift.py which prevents these from working. This is the subject of a revamp to how we represent robots in the Robotics Toolbox for Python which must be completed first.

**Comment by kxxt** [comment]
Thank you for creating Swift! it's very useful and enables me to simulate my robotic arm before putting it on real hardware. 😄🎉

**Comment by jhavl** [comment]
Glad you find it useful! For simulating your robot, if you haven't already done so, I would recommend making a custom URDF, or defining an ETS model as seen [here](https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/models/ETS/GenericSeven.py) - if you currently have a DH model.

**Pull request merged**
